### ISSUE TITLE
Feature types are out of date

### ISSUE THREAD

**Issue by iboates** [TatjanaKutzner/CityGML-UtilityNetwork-ADE#10]
I believe that the feature types file (`./FME/CityGML_UtilityNetworkADE_feature_types.xml`) is out of date. I went to go look for `ConnectionComponent`, which is a new element, but it is not there. @TatjanaKutzner Would you be able to upload the latest version?

**Comment by iboates** [comment]
Also, the line which is supposed to validate the namespace in this file still reads `xmlns:utility="http://www.citygml.org/ade/utility/0.9.2"`. I don't know how this is working because going to that link in a browser results in a dead page. Changing it to `xmlns:utility="http://www.citygml.org/ade/utility/0.9.3"` just stops the feature types from validating at all, and they no longer appear in the "Import Feature Types" dialog.

**Comment by TatjanaKutzner** [comment]
Thanks a lot for your feedback.

I updated the feature types file and also replaced `xmlns:utility="http://www.citygml.org/ade/utility/0.9.2"` by `xmlns:utility="http://www.citygml.org/ade/utility/0.9.3"` in all files.
The feature types should now appear again in the "Import Feature Types" dialog.

I recreated the release so that these changes are included.
